blank_issues_enabled: false
contact_links:
  - name: 📩 Contacto por email
    url: mailto:conectandocorazones.plataforma@gmail.com # TO-DO: Cambiar por el email de contacto
    about: Si necesitás contactarte directamente con el equipo de desarrollo.